const cseSubjects = {
  2019: {
    1: [
      { code: "JHS1121", name: "Communicative English and Soft Skills I" },
      { code: "JMA1101", name: "Matrices and Calculus" },
      { code: "JPH1101", name: "Engineering Physics" },
      { code: "JCY1101", name: "Engineering Chemistry" },
      { code: "JGE1101", name: "Engineering Basics" },
      { code: "JGE1102", name: "Programming in C" },
      { code: "JPC1111", name: "Physics and Chemistry Laboratory" },
      { code: "JGE1112", name: "Programming in C Laboratory" },
      { code: "JGE1111", name: "Design Appreciation Laboratory" },
    ],
    2: [
      { code: "JHS1221", name: "Technical English and Soft Skills II" },
      { code: "JMA1201", name: "Vector Calculus and Complex Analysis" },
      {
        code: "JBE1223",
        name: "Applied Science for Electronics and Information Engineering",
      },
      { code: "JGE1201", name: "Python Programming" },
      { code: "JEC1204", name: "Digital Logic Fundamentals" },
      { code: "JGE1202", name: "Engineering Graphics & Design" },
      { code: "JNC1261", name: "Environmental Science" },
      { code: "JGE1211", name: "Python Programming Laboratory" },
      { code: "JEC1214", name: "Digital Logic Fundamentals Laboratory" },
    ],
    3: [
      { code: "JMA1303", name: "Discrete Mathematics and Number Theory" },
      { code: "JCS1301", name: "Data Structures" },
      { code: "JCS1302", name: "Database Management Systems" },
      { code: "JCS1303", name: "Computer Architecture" },
      { code: "JCS1321", name: "Object Oriented Programming (Integrated)" },
      { code: "JPT1001", name: "Soft Skill and Aptitude-I" },
      { code: "JCS1311", name: "Data Structures Laboratory" },
      { code: "JCS1312", name: "Database Management Systems Laboratory" },
    ],
    4: [
      { code: "JMA1403", name: "Applied Probability and Queuing Theory" },
      { code: "JCS1401", name: "Computer Networks" },
      { code: "JCS1402", name: "Operating Systems" },
      { code: "JCS1403", name: "Design and Analysis of Algorithms" },
      { code: "JCS1404", name: "Software Engineering" },
      { code: "Open Elective-I", name: "Open Elective-I" },
      { code: "JPT1001", name: "Soft Skills and Aptitude-II" },
      { code: "JCS1411", name: "Networks Laboratory" },
      { code: "JCS1412", name: "Operating Systems Laboratory" },
    ],
    5: [
      { code: "JCS1501", name: "Internet Programming" },
      {
        code: "JCS1502",
        name: "Object Oriented Analysis and Design (Integrated)",
      },
      { code: "JCS1503", name: "Theory of Computation" },
      { code: "Professional-Elective-I", name: "Professional Elective - I" },
      { code: "Open Elective-II", name: "Open Elective-II" },
      { code: "JPT1002", name: "Technical Skills and Aptitude-I" },
      { code: "JHS1511", name: "Professional Communication" },
      { code: "JCS1511", name: "Internet Programming Laboratory" },
    ],
    6: [
      { code: "JCS1601", name: "Compiler Design" },
      { code: "JIT1602", name: "Artificial Intelligence" },
      { code: "JCS1603", name: "Cryptography and Network Security" },
      { code: "Professional-Elective-II", name: "Professional Elective - II" },
      { code: "Professional-Elective-III", name: "Professional-Elective-III" },
      { code: "Open-Elective-III", name: "Open Elective - III" },
      { code: "JPT1002", name: "Technical Skills and Aptitude-II" },
      { code: "JCS1611", name: "Compiler Design Laboratory" },
      { code: "JCS1621", name: "Mini Project" },
      { code: "JCS1641", name: "Internship" },
    ],
    7: [
      { code: "JCS1701", name: "Big Data Analytics" },
      { code: "JCS1702", name: "Cloud Computing (Integrated)" },
      { code: "Professional-Elective-IV", name: "Professional-Elective-IV" },
      { code: "Open-Elective-IV", name: "Open Elective -IV" },
      { code: "JNC1361", name: "Essence of Indian Traditional Knowledge" },
      { code: "JBA1711", name: "Entrepreneurship for Engineers" },
      {
        code: "NMS0001",
        name: "Professional Readiness for Innovation, Employability and Entrepreneurship",
      },
      { code: "JCS1711", name: "Big Data Analytics Laboratory" },
      { code: "JCS1731", name: "Project work – Phase I" },
    ],
    8: [
      { code: "JNC1861", name: "Indian Constitution" },
      { code: "JCS1851", name: "Comprehension and Technical Seminar" },
      { code: "JCS1832", name: "Project work – Phase II" },
    ],
  },
  2021: {
    1: [
      { code: "JHS1221", name: "Technical English and Soft Skills II" },
      { code: "JMA1201", name: "Vector Calculus and Complex Analysis" },
      {
        code: "JBE1223",
        name: "Applied Science for Electronics and Information Engineering",
      },
      { code: "JGE1201", name: "Python Programming" },
      { code: "JEC1204", name: "Digital Logic Fundamentals" },
      { code: "JGE1202", name: "Engineering Graphics & Design" },
      { code: "JNC1261", name: "Environmental Science" },
      { code: "JGE1211", name: "Python Programming Laboratory" },
      { code: "JEC1214", name: "Digital Logic Fundamentals Laboratory" },
    ],
    2: [{ code: "JEC1214", name: "Digital Logic Fundamentals Laboratory" }],
  },
};

export default cseSubjects;
